services:
  db:
    image: postgres:15-alpine
    container_name: sent_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Thanh@123"
      POSTGRES_DB: sent_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sent_net

  mongodb:
    image: mongo:6.0
    container_name: sent_mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - sent_net

  redis:
    image: redis:7-alpine  
    container_name: sent_redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - sent_net

  nats:
    image: nats:latest
    container_name: sent_nats
    restart: always
    networks:
      - sent_net

  
  auth-service:
    build: 
      context: ./SENT_backend
      dockerfile: service/auth/Dockerfile
    container_name: auth_service
    env_file: .env
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis
    networks:
      - sent_net

  asset-service:
    build:
      context: ./SENT_backend         
      dockerfile: service/assets/Dockerfile
    container_name: asset_service
    env_file: .env
    ports:
      - "8002:8000"
    depends_on:
      - db
      - mongodb
    networks:
      - sent_net

  behavior-service:
    build:
      context: ./SENT_backend
      dockerfile: service/behavior/Dockerfile
    container_name: behavior_service
    env_file: .env
    ports:
      - "8003:8000"
    depends_on:
      - mongodb
      - nats
    networks:
      - sent_net

  dashboard-service:
    build:
      context: ./SENT_backend
      dockerfile: service/dashboard/Dockerfile
    container_name: dashboard_service
    env_file: .env
    ports:
      - "8004:8000"
    depends_on:
      - db
      - mongodb
    networks:
      - sent_net

  incident-service:
    build:
      context: ./SENT_backend
      dockerfile: service/incidents/Dockerfile
    container_name: incident_service
    env_file: .env
    ports:
      - "8005:8000"
    depends_on:
      - db
      - mongodb
    volumes:
      - ./uploads/audits:/app/uploads/audits
    networks:
      - sent_net

  policy-service:
    build: 
      context: ./SENT_backend
      dockerfile: service/policies/Dockerfile
    container_name: policy_service
    env_file: .env
    ports:
      - "8006:8000"
    depends_on:
      - db
    networks:
      - sent_net

  document-service:
    build: 
      context: ./SENT_backend
      dockerfile: service/documents/Dockerfile
    container_name: document_service
    env_file: .env
    ports:
      - "8007:8000"
    depends_on:
      - db
      - gotenberg 
    volumes:
      - ./uploads/documents:/app/uploads/documents
      - ./uploads/pdf_previews:/app/uploads/pdf_previews
    networks:
      - sent_net

  ai-service:
    build:
      context: ./SENT_backend
      dockerfile: service/ai/Dockerfile
    container_name: ai_service
    env_file: .env
    ports:
      - "8008:8000"
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434
    depends_on: 
      - db
      - mongodb
    networks:
      - sent_net

  groups-service:
    build:
      context: ./SENT_backend
      dockerfile: service/groups/Dockerfile
    container_name: groups_service
    env_file: .env
    ports:
      - "8009:8000"
    networks:
      - sent_net

  scoring-service:
    build:
      context: ./SENT_backend
      dockerfile: service/scoring/Dockerfile
    container_name: scoring_service
    env_file: .env
    ports:
      - "8010:8000"
    depends_on:
      - db
    networks:
      - sent_net

  user-service:
    build:
      context: ./SENT_backend
      dockerfile: service/users/Dockerfile
    container_name: user_service
    env_file: .env
    ports:
      - "8011:8000"
    depends_on:
      - db
      - redis
    networks:
      - sent_net

  software-service:
    build:
      context: ./SENT_backend
      dockerfile: service/software/Dockerfile
    container_name: software_service
    env_file: .env
    ports:
      - "8012:8000"
    depends_on:
      - db
      - mongodb
    networks:
      - sent_net
  approval-service:
    build:
      context: ./SENT_backend
      dockerfile: service/approvals/Dockerfile
    container_name: approval_service
    env_file: .env
    ports:
      - "8013:8000"
    depends_on:
      - db
      - redis
    networks:
      - sent_net

  frontend:
    build:
      context: ./SENT_frontend
      args:
        - VITE_API_URL=/api/v1
    container_name: sent_frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - auth-service
      - asset-service
    networks:
      - sent_net
  
  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: sent_converter
    restart: always
    networks:
      - sent_net

  sent-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: sent_tunnel
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    restart: always
    networks:
      - sent_net
  #just use when hace a strong PC
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: sent_ollama
  #   volumes:
  #     - ollama_data:/root/.ollama 
  #   networks:
  #     - sent_net
networks:
  sent_net:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  redis_data:
  ollama_data: