version: '3.8'

services:
  # 1. DATABASE (PostgreSQL)
  db:
    image: postgres:16
    container_name: sent_db_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Thanh@123
      POSTGRES_DB: sent_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. BACKEND (Go Gin)
  backend:
    build: ./SENT_backend
    container_name: sent_backend
    ports:
      - "8000:8000"
    environment:
      # Kết nối trực tiếp tới container 'db'
      - DATABASE_URL=postgres://postgres:Thanh@123@db:5432/sent_db?sslmode=disable
    depends_on:
      - db

  # 3. FRONTEND (React)
  frontend:
    build: ./SENT_frontend
    container_name: sent_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: